name: mime_types
version: 0.0.1
description: A helper-package for working MIME and content types.
author: Todd Mannherz <todd.mannherz@gmail.com>
homepage: https://github.com/tmannherz/mime_types
environment:
  sdk: '>=1.20.1 <2.0.0'
dev_dependencies:
  test:
