name: mime_types
description: A helper-package for working MIME and content types.
version: 0.0.1
author: Todd Mannherz <todd.mannherz@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test:
